Interface spectral fix
finos-labs/architecture-as-code pull request #124
Opened 2024-04-04 16:04 UTC by willosborne

Fix spectral rules for instantiations + add new rule to check interfaces exist.
Also move files to prepare for pattern flavour of spectral rules and update spectral workflow

2024-04-05 09:18 UTC, jpgough-ms requested changes
Looks like traders.json needs a few upgrades

2024-04-05 09:18 UTC, jpgough-ms commented on .vscode/settings.json
> +        "https://json.schemastore.org/yamllint.json": "file:///home/will/code/architecture-as-code/spectral/instantiation/validation-rules.yaml"
It looks like this one probably should not get checked in? Do we have a .gitignore for this?

2024-04-08 08:45 UTC, rocketstack-matt commented on calm/samples/api-gateway-implementation.json
Shouldn't the placeholders be replaced with actual values in the in the implementation and the pattern file should be updated to include the host and port placeholders in the interfaces?

2024-04-10 13:06 UTC, willosborne commented on calm/samples/api-gateway-implementation.json
This file is meant to look like what would be output by a generate command, as I understand it. i.e. it's ready to be filled out by a user by replacing the placeholders.

The pattern file should have properties defined without a value - e.g 
host: {
  type: "string"
}

Then the placeholders are generated from this.

Sorry if I've misunderstood something!

2024-04-10 16:39 UTC, rocketstack-matt commented on calm/samples/api-gateway-implementation.json
I don't think that's right. This folder should contain real samples that we're providing almost as documentation / guides for users and therefore implementations should be 'working' so to speak (I appreciate this is already wrong, not being changed to this in your PR).

I think if we want an example of the 'interim state' implementation that would be generated by the CLI then we should put that in the CLI project either as an example or as a test file.

2024-04-12 13:22 UTC, willosborne commented on calm/samples/api-gateway-implementation.json
This makes sense, happy to apply this update later. But I think this should be on a separate PR.

2024-04-12 13:25 UTC, rocketstack-matt commented on calm/samples/api-gateway-implementation.json
I'm fine with that.
- [ ] Correct the sample implementations to now have any placeholders

2024-04-12 13:52 UTC, rocketstack-matt approved these changes

2024-04-15 09:53 UTC, lbulanti-ms approved these changes

2024-04-15 09:53 UTC, merged