Issue#10 Initial suggested change for strongly typed relationships
finos-labs/architecture-as-code pull request #30
Opened 2024-02-23 20:06 UTC by Budlee

An suggested change to the relationships types to make them strongly typed.

2024-02-23 20:07 UTC, Budlee commented
@rocketstack-matt and @jpgough-ms , this is just a sample to get thoughts on the changes of strongly typed relationships. If this is seen as a good idea I'll update the API Pattern example as well

2024-02-27 20:01 UTC, jpgough-ms requested changes
Overall I like this approach, but I think the `oneOf` will clarify what is strictly needed on a relationship

2024-02-27 20:48 UTC, aidanm3341 commented
I support this change! While building the visualiser, I had actually assumed that these were already strongly typed.

2024-02-27 20:55 UTC, aidanm3341 commented
I like baking these types into the schema - but if for any reason we didn't want to change the schema in this way, an alternative would be to create a spectral ruleset that checks for the existence of the required fields given some 'relationship-type'

2024-02-28 20:47 UTC, Budlee commented on calm/draft/2024-02/meta/core.json
> +          "type": "array",
Like that a lot

2024-02-28 22:08 UTC, Budlee commented on calm/draft/2024-02/meta/core.json
> +            "connects": {
Yep, I'll apply that

2024-03-01 11:10 UTC, rocketstack-matt requested changes
I like the proposal, if you can get this tidied up and ready to push @Budlee I think we'll be happy to make this change.

2024-03-01 11:10 UTC, rocketstack-matt commented on calm/samples/traderx/traderx.json
> +  "$schema": "../../../calm/draft/2024-02/meta/calm.json",
Should remain full path

2024-03-01 11:10 UTC, rocketstack-matt commented on calm/samples/traderx/traderx.json
> +      "relationship-t": ""
Looks like a typo - should remove this line

2024-03-01 11:10 UTC, rocketstack-matt commented on calm/samples/traderx/traderx.json
> +        "deployed-in": {
Minor point but should we change the deployed-in to show the container first, does it read more naturally?

2024-03-01 11:10 UTC, rocketstack-matt commented on calm/samples/traderx/traderx.yaml
> +$schema:  ../../../calm/draft/2024-02/meta/calm.json
Full path

2024-03-01 12:00 UTC, Budlee commented
I’ll add these suggestions in. The bulk of it I completed yesterday and was just doing the tidy up. Send

2024-03-03 21:06 UTC, Budlee commented on calm/samples/traderx/traderx.json
> +  "$schema": "../../../calm/draft/2024-02/meta/calm.json",
reverted

2024-03-03 21:17 UTC, Budlee commented
@rocketstack-matt , @aidanm3341  and @jpgough-ms I'd appreciate any additional feedback. All the suggestions have been mare

2024-03-04 12:16 UTC, rocketstack-matt commented on calm/draft/2024-02/meta/core.json
> +          "type": "array",
I see we now have minItems, but don't we need it to be at least 1? In fact, in the case of nodes should it be at least 2 and in the case of relationships at least 1?

2024-03-04 19:05 UTC, Budlee commented on calm/draft/2024-02/meta/core.json
> +          "type": "array",
Updated

2024-03-05 08:38 UTC, rocketstack-matt approved these changes

2024-03-05 10:06 UTC, Budlee commented on calm/draft/2024-02/meta/calm.json
> +    {"$ref": "core.json"}
This was reverted

2024-03-06 21:34 UTC, Budlee commented
@jpgough-ms can you check the changes you requested, these should be done.

2024-03-07 09:38 UTC, jpgough-ms requested changes
@rocketstack-matt should this be in `draft/2024-03/meta` this is going to break patterns (as demonstrated by the need to change the samples).

2024-03-07 10:46 UTC, rocketstack-matt commented
That's a very good point, I guess it should be, even by the guidelines we were discussing on the last call, but especially with it creating breaking change.

2024-03-07 10:48 UTC, rocketstack-matt commented
@Budlee per @jpgough-ms's comment would you be able to raise this change as a new draft. That will also require that we version the samples so we have the old and new versions.

2024-03-07 10:48 UTC, closed without merging